version: "3.7"

networks:
  mainflux-base-net:

services:
  mqtt-adapter:
    image: amdm/aproxy:${APROXY_RELEASE_TAG}
    container_name: mainflux-mqtt
    restart: on-failure
    environment:
      APROXY_MQTT_ADAPTER_LOG_LEVEL: ${APROXY_MQTT_ADAPTER_LOG_LEVEL}
      APROXY_MQTT_ADAPTER_MQTT_PORT: ${APROXY_MQTT_ADAPTER_MQTT_PORT}
      APROXY_MQTT_ADAPTER_MQTT_TARGET_HOST: ${APROXY_MQTT_ADAPTER_MQTT_TARGET_HOST}
      APROXY_MQTT_ADAPTER_MQTT_TARGET_PORT: ${APROXY_MQTT_ADAPTER_MQTT_TARGET_PORT}
      APROXY_MQTT_ADAPTER_FORWARDER_TIMEOUT: ${APROXY_MQTT_ADAPTER_FORWARDER_TIMEOUT}
      APROXY_MQTT_ADAPTER_MQTT_TARGET_HEALTH_CHECK: ${APROXY_MQTT_ADAPTER_MQTT_TARGET_HEALTH_CHECK}
      APROXY_MQTT_ADAPTER_WS_PORT: ${APROXY_MQTT_ADAPTER_WS_PORT}
      APROXY_MQTT_ADAPTER_INSTANCE_ID: ${APROXY_MQTT_ADAPTER_INSTANCE_ID}
      APROXY_MQTT_ADAPTER_WS_TARGET_HOST: ${APROXY_MQTT_ADAPTER_WS_TARGET_HOST}
      APROXY_MQTT_ADAPTER_WS_TARGET_PORT: ${APROXY_MQTT_ADAPTER_WS_TARGET_PORT}
      APROXY_MQTT_ADAPTER_WS_TARGET_PATH: ${APROXY_MQTT_ADAPTER_WS_TARGET_PATH}
      APROXY_MQTT_ADAPTER_INSTANCE: ${APROXY_MQTT_ADAPTER_INSTANCE}
      APROXY_MQTT_ADAPTER_ES_URL: ${APROXY_MQTT_ADAPTER_ES_URL}
      APROXY_MQTT_ADAPTER_ES_PASS: ${APROXY_MQTT_ADAPTER_ES_PASS}
      APROXY_MQTT_ADAPTER_ES_DB: ${APROXY_MQTT_ADAPTER_ES_DB}
      APROXY_THINGS_AUTH_GRPC_URL: ${APROXY_THINGS_AUTH_GRPC_URL}
      APROXY_THINGS_AUTH_GRPC_TIMEOUT: ${APROXY_THINGS_AUTH_GRPC_TIMEOUT}
      APROXY_THINGS_AUTH_GRPC_CLIENT_TLS: ${APROXY_THINGS_AUTH_GRPC_CLIENT_TLS}
      APROXY_THINGS_AUTH_GRPC_CA_CERTS: ${APROXY_THINGS_AUTH_GRPC_CA_CERTS}
      APROXY_JAEGER_URL: ${APROXY_JAEGER_URL}
      APROXY_SEND_TELEMETRY: ${APROXY_SEND_TELEMETRY}
    networks:
      - mainflux-base-net
    volumes:
      - ../configs/config.toml:/config.toml
